name: Builds and deploys the container

on:
  # Trigger the workflow on push but only for the master branch
  push:
    branches:
      - master
      - rebuild-droplet-when-container-built

jobs:
  build_image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get the short SHA of the commit
        id: vars
        run: |
          IMAGE_TAG=$(git rev-parse --short=7 $GITHUB_SHA)
          echo ::set-output name=image_tag::$IMAGE_TAG
          echo 'IMAGE_TAG:' $IMAGE_TAG
      # - name: Publish latest tag to GitHub Packages
      #   uses: matootie/github-docker@v2.2.2
      #   with:
      #     accessToken: ${{ secrets.GITHUB_TOKEN }}
      #     imageTag: "latest"
      - name: Publish short SHA tag to GitHub Packages
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          imageTag: ${{ steps.vars.outputs.image_tag }}
      - name: Rebuild droplet
        if: success()
        run: |
          curl -s -f \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${DIGITALOCEAN_API_KEY}" \
            -d {"type": "rebuild", "image": "docker-18-04"} \
            "https://api.digitalocean.com/v2/droplets/${DIGITALOCEAN_DROPLET_ID}/actions"
        env:
          DIGITALOCEAN_API_KEY: ${{ secrets.DIGITALOCEAN_API_KEY }}
          DIGITALOCEAN_DROPLET_ID: ${{ secrets.DIGITALOCEAN_DROPLET_ID }}
